<?php
declare(strict_types=1);
const APP_ROOT = __DIR__ . '/..';
const CONFIG_FILE = APP_ROOT . '/config/config.php';
const LOG_FILE = APP_ROOT . '/storage/logs/app.log';
const MAX_HTTP_BYTES = 2097152;
if (session_status() === PHP_SESSION_NONE) {
    $secure = (!empty($_SERVER['HTTPS']) && strtolower((string)$_SERVER['HTTPS']) !== 'off');
    session_set_cookie_params(['lifetime'=>0,'path'=>base_path_for_cookie(),'secure'=>$secure,'httponly'=>true,'samesite'=>'Lax']);
    session_start();
}
function base_path_for_cookie(): string { return '/'; }
function app_config(): array { if(!is_file(CONFIG_FILE)) return []; try{ $config=require CONFIG_FILE; }catch(Throwable $e){ return []; } return is_array($config)?$config:[]; }
function installed(): bool { $c=app_config()['db']??[]; foreach(['host','name','user'] as $key){ if(!isset($c[$key]) || trim((string)$c[$key])==='') return false; } return true; }
function db_config(): array { return app_config()['db'] ?? []; }
function db(): PDO { static $pdo; if ($pdo) return $pdo; $config=app_config(); $c=$config['db']??[]; foreach(['host','name','user'] as $key){ if(!isset($c[$key])||$c[$key]==='') throw new RuntimeException('DB設定が不足しています。インストーラーで設定し直してください。'); } $pass=(string)($c['pass']??''); if(!empty($config['auto_setup'])){ $server=new PDO('mysql:host='.$c['host'].';charset=utf8mb4',(string)$c['user'],$pass,[PDO::ATTR_ERRMODE=>PDO::ERRMODE_EXCEPTION,PDO::ATTR_DEFAULT_FETCH_MODE=>PDO::FETCH_ASSOC]); $server->exec('CREATE DATABASE IF NOT EXISTS `'.str_replace('`','``',(string)$c['name']).'` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci'); } $dsn='mysql:host='.$c['host'].';dbname='.$c['name'].';charset=utf8mb4'; $pdo=new PDO($dsn,(string)$c['user'],$pass,[PDO::ATTR_ERRMODE=>PDO::ERRMODE_EXCEPTION,PDO::ATTR_DEFAULT_FETCH_MODE=>PDO::FETCH_ASSOC]); require_once __DIR__.'/schema.php'; create_schema($pdo); if(!empty($config['auto_setup'])) auto_setup($pdo,$config); return $pdo; }
function database_available(): bool { try { db(); return true; } catch (Throwable $e) { return false; } }
function database_error_message(Throwable $e): string { log_event('error','DB接続失敗',$e->getMessage()); return 'DBへ接続できません。config/config.php のDB情報を確認するか、/install/ から設定し直してください。'; }
function auto_setup(PDO $pdo,array $config): void { seed_settings($config['settings']??[]); }
function e($v): string { return htmlspecialchars((string)$v, ENT_QUOTES | ENT_SUBSTITUTE, 'UTF-8'); }
function base_path(): string { $script=(string)($_SERVER['SCRIPT_NAME']??''); foreach(['/admin/','/install/','/cron/'] as $dir){ $pos=strpos($script,$dir); if($pos!==false) return rtrim(substr($script,0,$pos),'/'); } return rtrim(str_replace('\\','/',dirname($script)),'/'); }
function app_url(string $path): string { return base_path().'/'.ltrim($path,'/'); }
function request_scheme(): string { $https=strtolower((string)($_SERVER['HTTPS']??'')); return $https!==''&&$https!=='off'?'https':'http'; }
function app_absolute_url(string $path): string { return request_scheme().'://'.($_SERVER['HTTP_HOST']??'localhost').app_url($path); }
function redirect(string $url): never { header('Location: '.(str_starts_with($url,'/')?app_url($url):$url)); exit; }
function csrf_token(): string { if(empty($_SESSION['csrf'])) $_SESSION['csrf']=bin2hex(random_bytes(32)); return $_SESSION['csrf']; }
function verify_csrf(): void { if(($_POST['csrf']??'')!==($_SESSION['csrf']??'')){ http_response_code(400); exit('不正なリクエストです。画面を再読み込みして再度お試しください。'); } }
function is_admin(): bool { return !empty($_SESSION['admin_id']); }
function require_admin(): void { if(!is_admin()) redirect('/admin/login.php'); }
function setting(string $key, $default=null){ $st=db()->prepare('SELECT value FROM settings WHERE name=?'); $st->execute([$key]); $v=$st->fetchColumn(); return $v===false?$default:$v; }
function set_setting(string $key, string $value): void { $st=db()->prepare('INSERT INTO settings(name,value) VALUES(?,?) ON DUPLICATE KEY UPDATE value=VALUES(value)'); $st->execute([$key,$value]); }
function mask_secret(string $s): string { return preg_replace('/([A-Za-z0-9_\-]{8})[A-Za-z0-9_\-]{8,}/','${1}...', $s) ?? $s; }
function log_event(string $level,string $message,string $context=''): void { $context=mask_secret($context); @is_dir(dirname(LOG_FILE)) || @mkdir(dirname(LOG_FILE),0755,true); @file_put_contents(LOG_FILE, '['.date('c')."] $level $message $context\n", FILE_APPEND|LOCK_EX); if(installed()){ try{ $st=db()->prepare('INSERT INTO logs(level,message,context,created_at) VALUES(?,?,?,NOW())'); $st->execute([$level,$message,$context]); }catch(Throwable $e){} } }
function valid_url(string $url): bool { return is_safe_public_url($url,false); }
function is_safe_public_url(string $url,bool $checkDns=true): bool { if(!filter_var($url,FILTER_VALIDATE_URL)) return false; $p=parse_url($url); if(!in_array(strtolower((string)($p['scheme']??'')),['http','https'],true)) return false; $host=(string)($p['host']??''); if($host==='' || preg_match('/(^|\.)localhost$/i',$host)) return false; if(filter_var($host,FILTER_VALIDATE_IP)) return (bool)filter_var($host,FILTER_VALIDATE_IP,FILTER_FLAG_NO_PRIV_RANGE|FILTER_FLAG_NO_RES_RANGE); if($checkDns){ $ips=[]; if(false) $ips[]=$host; else { $a=@dns_get_record($host,DNS_A|DNS_AAAA); foreach($a?:[] as $r) $ips[]=$r['ip']??$r['ipv6']??''; } if(!$ips) return false; foreach($ips as $ip) if(!filter_var($ip,FILTER_VALIDATE_IP,FILTER_FLAG_NO_PRIV_RANGE|FILTER_FLAG_NO_RES_RANGE)) return false; } return true; }
function http_request(string $method,string $url,array $headers=[],?string $body=null,array $opts=[]): array { if(!is_safe_public_url($url,true)) throw new RuntimeException('URLが正しくないか、内部ネットワークを指しています'); $timeout=(int)($opts['timeout']??15); $max=(int)($opts['max_bytes']??MAX_HTTP_BYTES); if(function_exists('curl_init')){ $ch=curl_init($url); curl_setopt_array($ch,[CURLOPT_CUSTOMREQUEST=>$method,CURLOPT_HTTPHEADER=>$headers,CURLOPT_RETURNTRANSFER=>true,CURLOPT_HEADER=>true,CURLOPT_TIMEOUT=>$timeout,CURLOPT_CONNECTTIMEOUT=>10,CURLOPT_FOLLOWLOCATION=>false,CURLOPT_USERAGENT=>'livedoor-antenna/1.0 (+https://example.invalid)',CURLOPT_MAXREDIRS=>0]); if($body!==null) curl_setopt($ch,CURLOPT_POSTFIELDS,$body); $res=curl_exec($ch); if($res===false){$err=curl_error($ch); curl_close($ch); throw new RuntimeException(stripos($err,'timed')!==false?'タイムアウトしました':'接続できませんでした');} $hs=curl_getinfo($ch,CURLINFO_HEADER_SIZE); $code=(int)curl_getinfo($ch,CURLINFO_RESPONSE_CODE); $ct=(string)curl_getinfo($ch,CURLINFO_CONTENT_TYPE); $head=substr((string)$res,0,$hs); $data=substr((string)$res,$hs,$max+1); curl_close($ch); } else { $ctx=stream_context_create(['http'=>['method'=>$method,'header'=>implode("\r\n",array_merge(['User-Agent: livedoor-antenna/1.0'],$headers)),'content'=>$body??'','timeout'=>$timeout,'ignore_errors'=>true,'follow_location'=>0]]); $data=@file_get_contents($url,false,$ctx,0,$max+1); if($data===false) throw new RuntimeException('接続できませんでした'); $head=implode("\n",$http_response_header??[]); $code=0; foreach($http_response_header??[] as $hh) if(preg_match('/HTTP\/\S+\s+(\d+)/',$hh,$m)) $code=(int)$m[1]; $ct=''; foreach($http_response_header??[] as $hh) if(stripos($hh,'Content-Type:')===0) $ct=trim(substr($hh,13)); }
    if(preg_match('/^Location:\s*(\S+)/im',$head,$m) && !is_safe_public_url(resolve_url($url,trim($m[1])),true)) throw new RuntimeException('リダイレクト先が内部ネットワークのため拒否しました');
    if(strlen($data)>$max) throw new RuntimeException('レスポンスサイズが上限を超えました'); return ['status'=>$code,'headers'=>$head,'body'=>$data,'content_type'=>$ct]; }
function resolve_url(string $base,string $loc): string { if(preg_match('#^https?://#i',$loc)) return $loc; $p=parse_url($base); return ($p['scheme']??'http').'://'.($p['host']??'').(str_starts_with($loc,'/')?$loc:'/'.ltrim($loc,'/')); }
function http_get(string $url): string { $r=http_request('GET',$url,[],null,['timeout'=>15]); if($r['status']<200||$r['status']>=300) throw new RuntimeException('HTTP '.$r['status']); if($r['content_type'] && !preg_match('#(xml|rss|atom|text/html|text/plain)#i',$r['content_type'])) throw new RuntimeException('RSS/AtomではないContent-Typeです'); return $r['body']; }
function ensure_cron_token(): string { $t=(string)setting('cron_token',''); if(strlen($t)<48){ $t=bin2hex(random_bytes(32)); set_setting('cron_token',$t); } return $t; }
function protect_cron(string $name, callable $fn): void { if(PHP_SAPI!=='cli'){ $token=(string)($_GET['token']??''); if($token==='' || !hash_equals(ensure_cron_token(),$token)){ http_response_code(403); echo "FORBIDDEN\n"; return; } } $lock=fopen(sys_get_temp_dir().'/la_'.$name.'.lock','c'); if(!$lock || !flock($lock,LOCK_EX|LOCK_NB)){ log_event('warning','Cron多重実行をスキップ',$name); echo "SKIPPED\n"; return; } try{ $fn(); } finally { flock($lock,LOCK_UN); fclose($lock); } }
function admin_header(string $title): void { if(!installed() || !database_available()) redirect('/install/'); require_admin(); $site=e(setting('site_name','livedoorアンテナ')); echo "<!doctype html><html lang=ja><head><meta charset=utf-8><meta name=viewport content='width=device-width,initial-scale=1'><link rel=stylesheet href='".app_url('/assets/admin.css')."'><title>".e($title)." - $site</title></head><body><aside><h1>$site</h1><nav>"; foreach(['index.php'=>'ダッシュボード','feeds.php'=>'RSS管理','articles.php'=>'記事一覧','posts.php'=>'投稿履歴','settings.php'=>'基本設定','livedoor.php'=>'livedoor設定','cron.php'=>'Cron設定','logs.php'=>'ログ','logout.php'=>'ログアウト'] as $u=>$l) echo "<a href='".app_url('/admin/'.$u)."'>".e($l)."</a>"; echo "</nav></aside><main><h2>".e($title)."</h2>"; }
function admin_footer(): void { echo '</main></body></html>'; }
