<?php
require_once __DIR__.'/rss.php';
function select_articles(int $limit): array { $limit=max(1,$limit); $rows=db()->query('SELECT a.*,f.site_name,(SELECT MAX(ph.posted_at) FROM post_items pi JOIN post_history ph ON ph.id=pi.post_id JOIN articles aa ON aa.id=pi.article_id WHERE aa.feed_id=a.feed_id AND ph.result="OK") last_feed_post FROM articles a JOIN feeds f ON f.id=a.feed_id WHERE a.selected=0 AND a.last_post_id IS NULL ORDER BY COALESCE(a.published_at,a.fetched_at) DESC LIMIT 300')->fetchAll(); $pool=[];$seen=[]; foreach($rows as $r){ if(isset($seen[$r['url']]) || !valid_url($r['url'])) continue; $seen[$r['url']]=1; $pool[]=$r; } $sel=[];$per=[]; while(count($sel)<$limit && $pool){ $bestKey=null;$best=-INF; foreach($pool as $k=>$r){ $ts=strtotime($r['published_at']?:$r['fetched_at'])?:time(); $ageHours=max(0,(time()-$ts)/3600); $score=1000-min($ageHours,240); $score-=($per[$r['feed_id']]??0)*36; if(empty($r['last_feed_post'])||strtotime($r['last_feed_post'])<time()-86400*3)$score+=18; if($r['image_url']) $score+=2; if($score>$best){$best=$score;$bestKey=$k;} } if($bestKey===null) break; $pick=$pool[$bestKey]; unset($pool[$bestKey]); $sel[]=$pick; $per[$pick['feed_id']]=($per[$pick['feed_id']]??0)+1; } return $sel; }
function clean_title(string $t): string { $t=preg_replace('/^【[^】]{1,20}】\s*/u','',$t); $t=preg_replace('/^[\[\(（【][^\]\)）】]{1,20}[\]\)）】]\s*/u','',$t); $t=preg_replace('/\s*[|｜\-–—:：]\s*[^|｜\-–—:：]{1,30}$/u','',$t); return trim(preg_replace('/[\s　]+/u',' ',$t)); }
function choose_main(array $items): array { $best=null;$bs=-1; foreach($items as $i){$l=mb_strlen($i['title']); $s=($i['image_url']?4:0)+($l>=18&&$l<=55?3:0)+(preg_match('/！？|!|\?|動画|画像|速報|話題/u',$i['title'])?2:0)+random_int(0,3); if($s>$bs){$bs=$s;$best=$i;}} return $best?:$items[0]; }
function safe_link(string $url): string { return valid_url($url) ? $url : ''; }
function body_html(array $items): string { $h='<div class="la-antenna-post">'; $seen=[]; foreach($items as $i){$url=safe_link((string)$i['url']); if($url===''||isset($seen[$url])) continue; $seen[$url]=1; $title=(string)$i['title']; $h.='<a class="la-card" href="'.e($url).'" target="_blank" rel="noopener noreferrer">'; $img=safe_link((string)($i['image_url']??'')); if($img!=='') $h.='<span class="la-card-image-wrap"><img class="la-card-image" src="'.e($img).'" alt="'.e($title).'" loading="lazy"></span>'; $h.='<span class="la-card-title">'.e($title).'</span></a>'; } return $h.'</div>'; }
function atom_entry(string $title,string $body): string { return '<?xml version="1.0" encoding="utf-8"?><entry xmlns="http://www.w3.org/2005/Atom"><title>'.e($title).'</title><content type="html">'.e($body).'</content><updated>'.date('c').'</updated></entry>'; }
function livedoor_atompub_headers(string $user,string $pass,string $contentType='application/atom+xml;type=entry; charset=utf-8'): array { return ['Content-Type: '.$contentType,'Authorization: Basic '.base64_encode($user.':'.$pass)]; }
function validate_livedoor_atompub_settings(string $url): void { if(!valid_url($url)) throw new RuntimeException('ルートエンドポイントが正しくありません'); if(!preg_match('#^https://livedoor\.blogcms\.jp/atompub/[^/]+/article$#',$url)) throw new RuntimeException('ルートエンドポイントは https://livedoor.blogcms.jp/atompub/{BLOG_NAME}/article の形式で入力してください'); if(parse_url($url,PHP_URL_SCHEME)!=='https') throw new RuntimeException('HTTPSのルートエンドポイントを使用してください'); }
function livedoor_connection_test(): string { $url=setting('atompub_url',''); $user=setting('livedoor_id',''); $pass=setting('api_password',''); if($user==='') throw new RuntimeException('livedoor ID（ログイン用）が入力されていません'); if($pass==='') throw new RuntimeException('AtomPub用パスワードが入力されていません'); validate_livedoor_atompub_settings($url); $r=http_request('GET',$url,livedoor_atompub_headers($user,$pass,'application/atom+xml'),null,['timeout'=>15]); if($r['status']===401) throw new RuntimeException('認証に失敗しました。HTTP 401'); if($r['status']===403) throw new RuntimeException('投稿先ブログへアクセスできません。HTTP 403'); if($r['status']===404) throw new RuntimeException('ルートエンドポイントが正しくありません。HTTP 404'); if($r['status']<200||$r['status']>=300) throw new RuntimeException('livedoorへ接続できませんでした。HTTP '.$r['status']); return '接続テストに成功しました。記事は作成していません。'; }
function post_to_livedoor(string $title,string $body): array { $url=setting('atompub_url',''); $user=setting('livedoor_id',''); $pass=setting('api_password',''); if(!$url||!$user||!$pass) throw new RuntimeException('livedoor API設定が未入力です'); validate_livedoor_atompub_settings($url); $r=http_request('POST',$url,livedoor_atompub_headers($user,$pass),atom_entry($title,$body),['timeout'=>20]); if($r['status']<200||$r['status']>=300) throw new RuntimeException('APIエラー HTTP '.$r['status']); $loc=''; if(preg_match('/^Location:\s*(.+)$/im',$r['headers'],$m)) $loc=trim($m[1]); return ['url'=>$loc?:$url,'response'=>$r['body']]; }
function run_post(): int { $items=select_articles((int)setting('post_article_count',36)); if(!$items) throw new RuntimeException('投稿対象記事がありません'); $main=choose_main($items); $title=clean_title($main['title']); $body=body_html($items); $pdo=db(); try{$r=post_to_livedoor($title,$body); $pdo->beginTransaction(); $st=$pdo->prepare('INSERT INTO post_history(posted_at,main_title,livedoor_url,article_count,result,error,image_url,created_at) VALUES(NOW(),?,?,?,?,?,?,NOW())'); $st->execute([$title,$r['url'],count($items),'OK',null,$main['image_url']]); $pid=(int)$pdo->lastInsertId(); foreach($items as $i){ $pdo->prepare('INSERT INTO post_items(post_id,article_id) VALUES(?,?)')->execute([$pid,$i['id']]); $pdo->prepare('UPDATE articles SET selected=1,last_post_id=? WHERE id=?')->execute([$pid,$i['id']]); } $pdo->commit(); log_event('info','投稿成功','post_id='.$pid.' count='.count($items)); return $pid; }catch(Throwable $e){ if($pdo->inTransaction()) $pdo->rollBack(); $err=$e->getMessage(); try{ $pdo->beginTransaction(); $st=$pdo->prepare('INSERT INTO post_history(posted_at,main_title,livedoor_url,article_count,result,error,image_url,created_at) VALUES(NOW(),?,?,?,?,?,?,NOW())'); $st->execute([$title,'',count($items),'ERROR',$err,$main['image_url']]); $pdo->commit(); log_event('error','投稿失敗',$err); }catch(Throwable $historyError){ if($pdo->inTransaction()) $pdo->rollBack(); log_event('error','投稿失敗履歴の保存にも失敗',$historyError->getMessage()); } throw $e; } }
function cleanup_history(): void { $d=max(1,min(3650,(int)setting('history_retention_days',90))); $pdo=db(); $pdo->beginTransaction(); try{ $st=$pdo->prepare('SELECT id FROM post_history WHERE created_at < DATE_SUB(NOW(), INTERVAL '.$d.' DAY)'); $st->execute(); $ids=array_map('intval',$st->fetchAll(PDO::FETCH_COLUMN)); if($ids){ $in=implode(',',array_fill(0,count($ids),'?')); $pdo->prepare("DELETE FROM post_items WHERE post_id IN ($in)")->execute($ids); $pdo->prepare("DELETE FROM post_history WHERE id IN ($in)")->execute($ids); } $pdo->commit(); log_event('info','投稿履歴自動削除','deleted='.count($ids).' days='.$d); }catch(Throwable $e){$pdo->rollBack(); throw $e;} }
