<?php
function create_schema(PDO $pdo): void {
$pdo->exec("CREATE TABLE IF NOT EXISTS admins(id INT AUTO_INCREMENT PRIMARY KEY, username VARCHAR(100) UNIQUE NOT NULL, password_hash VARCHAR(255) NOT NULL, created_at DATETIME NOT NULL) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4");
$pdo->exec("CREATE TABLE IF NOT EXISTS settings(name VARCHAR(100) PRIMARY KEY, value TEXT NOT NULL) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4");
$pdo->exec("CREATE TABLE IF NOT EXISTS feeds(id INT AUTO_INCREMENT PRIMARY KEY, site_name VARCHAR(255) NOT NULL, feed_url TEXT NOT NULL, memo TEXT, sort_order INT NOT NULL DEFAULT 0, feed_type VARCHAR(20), last_fetched_at DATETIME NULL, last_result VARCHAR(20), last_error TEXT, created_at DATETIME NOT NULL, updated_at DATETIME NOT NULL) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4");
$pdo->exec("CREATE TABLE IF NOT EXISTS articles(id BIGINT AUTO_INCREMENT PRIMARY KEY, feed_id INT NOT NULL, title TEXT NOT NULL, url VARCHAR(1024) NOT NULL, image_url TEXT, published_at DATETIME NULL, fetched_at DATETIME NOT NULL, selected TINYINT(1) NOT NULL DEFAULT 0, last_post_id BIGINT NULL, UNIQUE KEY uniq_url(url(768)), INDEX idx_pub(published_at), INDEX idx_feed(feed_id)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4");
$pdo->exec("CREATE TABLE IF NOT EXISTS post_history(id BIGINT AUTO_INCREMENT PRIMARY KEY, posted_at DATETIME NOT NULL, main_title TEXT NOT NULL, livedoor_url TEXT, article_count INT NOT NULL, result VARCHAR(20) NOT NULL, error TEXT, image_url TEXT, created_at DATETIME NOT NULL) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4");
$pdo->exec("CREATE TABLE IF NOT EXISTS post_items(post_id BIGINT NOT NULL, article_id BIGINT NOT NULL, PRIMARY KEY(post_id,article_id)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4");
$pdo->exec("CREATE TABLE IF NOT EXISTS logs(id BIGINT AUTO_INCREMENT PRIMARY KEY, level VARCHAR(20) NOT NULL, message TEXT NOT NULL, context TEXT, created_at DATETIME NOT NULL, INDEX idx_created(created_at)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4");
}
function seed_settings(array $data): void { foreach($data as $k=>$v) set_setting($k,(string)$v); foreach(['rss_fetch_limit'=>20,'post_article_count'=>36,'post_interval_minutes'=>60,'history_retention_days'=>90,'cron_interval_minutes'=>60,'auto_update_enabled'=>0,'auth_method'=>'basic'] as $k=>$v) if(setting($k,null)===null) set_setting($k,(string)$v); }
